FROM node:12-alpine

LABEL Name=structure-base-nodejs Version=0.0.1

EXPOSE 5000
#Adjust localtime to your needs
#Set locale
ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir /app && chown node:node /app

USER node

WORKDIR /usr/src/app

COPY package.json package-lock.json* ./

RUN npm install --no-optional && npm cache clean --force

ENV PATH=/app/node_modules/.bin:$PATH

WORKDIR /app/node_app

CMD ["npm", "run", "dev"]